coralogix/protofetch

Cargo.lock, Cargo.toml, src/cli/args.rs, src/main.rs
I have found nothing nice for getting it from git tags, so ended up using the one from cargo.
This is mainly useful for `sbt-protodep` version checking of binaries.
=> Add command to get the binary version

.github/npm/getBinary.js, .github/npm/package.json, .github/workflows/release.yml
There're several issues that this PR is fixing:
* publish to the npm registry - tee doesn't seem to work properly when it's writing to the same file that is being read - so in the CI, temporary file was created for this purpose
* npm and I guess other tools too expect the binary to be located in the root tar.gz after unwrap, this was fixed by adding current directory in the packaging step instead of publishing all the file hierarchy including `target/release` directories.
=> Fix binary name to match location in the archive

.github/workflows/release.yml, Cargo.lock, Cargo.toml
For some reason it worked like that for the `npm` v6 but for 7 and 8 it's causing issues.
The `package.json` file should not contain `v` prefix - you can see it's there now:
https://www.npmjs.com/package/cx-protofetch/v/0.0.18?activeTab=explore
In the `npm` v6, it was automatically omitted for some reason but it didn't work in later `npm` versions.
=> Remove redundant v from the package json version

.github/workflows/release.yml, src/cache.rs
When releasing Linux binary, use switch `--target=x86_64-unknown-linux-musl` in order to get the binary working with various Linux distros (including alpine and older debian distros). So not require strict glibc dependency. It was failing in the service pipelines using debian images with the older glibc.
=> Fix Linux binary to work with various Linux distros

.github/workflows/ci.yml, rustfmt.toml, src/cache.rs, src/fetch.rs, src/lib.rs, src/proto_repository.rs
Nightly is a moving target, and the code that was properly formatted yesterday may be not formatted today. It also makes dev setup more complicated as you need both nightly and stable toolchains.
In the end, stable formatting is not so much worse, if at all.
=> Do not depend on nightly rust

.github/workflows/ci.yml
We even have a badge in the readme displaying CI workflow status, but we don't run it.
=> Run CI workflow on master

src/cache.rs, src/cli/mod.rs, src/main.rs
1. Do not warn about missing `GIT_USERNAME` and `GIT_PASSWORD` when we don't even know if we need them.
2. Use auth type for the actual protocol used by git, not for what we assume based on protofetch configuration. Git allows overriding repository URL, and it's not uncommon to have something like `url.git@github.com:.insteadof=https://github.com/`, when protofetch thinks it uses HTTPS, but libgit2 actually uses SSH.
3. Use git credential helper if we need HTTPS credentials and they have not been passed to protofetch explicitly.
4. Allow accessing public repositories by HTTPS without credentials (closes #34).
There is a [git2_credentials](https://crates.io/crates/git2_credentials) crate that supports git authentication even better (for example, it can get SSH username and identity from …
=> Use the correct auth type depending on the actual protocol

.github/npm/getBinary.js, .github/workflows/release.yml
"darwin_arm64" binaries we distribute are actually "darwin_amd64", and there is no easy way to cross-build to aarch64 because of the native dependencies.
=> Do not pretend like we have an aarch64-darwin build

.github/workflows/release.yml, Cargo.lock, Cargo.toml
Instead of always enabling the "vendored" feature of git2, only enable them when necessary (so, when building for linux with musl).
=> Use vendored dependencies on linux

.github/workflows/ci.yml
Downloading artifacts first doesn't work becase `cargo publish` checks that the workspace is clean. The simplest fix is to change the order.
=> Download artifacts after publishing to cargo

Cargo.lock, Cargo.toml
0.0.22 seems to be partially released (on cargo, but not on npm). Let's bump the version one more time to perform a clean release from the latest code.
=> Bump cargo package version

src/cache.rs, src/cli/command_handlers.rs, src/fetch.rs, src/lib.rs, src/model/protodep.rs, src/model/protofetch.rs, src/proto.rs, src/proto_repository.rs
https://doc.rust-lang.org/reference/names/preludes.html#extern-prelude
> Beginning in the 2018 edition <...> it is considered unidiomatic to use extern crate.
=> Replace extern crate with use

Cargo.lock, Cargo.toml, src/fetch.rs, src/model/protodep.rs, src/model/protofetch.rs, src/proto.rs
Mostly by simply wrapping them into `#[cfg(test)] mod tests { ... }`.
Besides following the common rust practices, this removes test-log dependency from the compile scope.
=> Move tests to the test configuration

src/api/builder.rs, src/api/mod.rs, src/cli/command_handlers.rs, src/main.rs
`--output-proto-directory` behavior seems to be not very useful when working with protofetch modules. It changes the default output directory, so it only works if the protofetch.toml file doesn't specify `proto_out_dir`. A more useful behavior seems to be to override the output directory, whether it's set in protofetch.toml or not.
This is technically a breaking change, but it is only breaking if someone has `proto_out_dir` set and is passing a different value to `--output-proto-directory` (which is then ignored).
=> Change --output-proto-directory behavior

src/api/builder.rs, src/cli/mod.rs, src/main.rs
It shouldn't be necessary to have credentials specified explicitly for protofetch, they should be part of the git configuration instead.
- `user.name` and `user.password` will not be read at all. I doubt anyone used it, as `user.name` is usually set to the first and last name of a person.
- `GIT_USERNAME` and `GIT_PASSWORD` will not work when using the API.
- `--username`, `--password`, `GIT_USERNAME` and `GIT_PASSWORD` will work in the CLI, but trigger a warning.
=> Deprecate explicit HTTP credentials

.github/workflows/ci.yml
`actions/download-artifact` creates subdirectories unless we download a specific artifact, so let's give it a meaningful name.
=> Fix artifacts not attached to GitHub releases

Cargo.lock, Cargo.toml, src/fetch.rs, src/model/protodep.rs, src/model/protofetch.rs, src/proto_repository.rs
1. Make `revision` optional.
2. Remove unused code for semantic versions support.
3. If both `branch` and `revision` are specified, verify that the `revision` belongs to a branch. Previously, `revision` was completely ignored, which was was very counter-intuitive.
Closes #32.
=> Make revision field optional

.github/workflows/ci.yml
For bsdtar <3.6.0 there seems to be no way to disable sparse files detection, macOS binary contains a region full of zeroes big enough to be detected as a hole, and node-tar cannot unpack such archives.
=> Use gtar instead of bsdtar

src/fetch.rs, src/model/protofetch/lock.rs
It is possible that the same dependency name refers to multiple repositories, and while this is hopefully not common, there may be valid reasons for that (for example, a protobuf definition that has been moved from one repository to another).
In order to support such cases, we need to:
1. When resolving conflicts, pick the repository of the "biggest" revision.
2. In the lock file, remember if some dependency was resolved from a different repository.
=> Remember what coordinate was resolved to a locked dependency

README.md
https://github.com/coralogix/protofetch/issues/32 changed the behavior of this field but didn't update the README.
=> `revision` should be documented as optional

src/api/builder.rs
This change modifies the `.protofetch/cache` string literal that is pushed onto a `PathBuf` to instead be two separate calls to `.push`, so that protofetch generates this path consistently on Windows and Unix.
=> Make the way the default cache directory is generated consistent on Windows

.github/workflows/ci.yml
Both the [npm package](https://github.com/coralogix/protofetch/blob/5cd349af19f5e2f29aecde0bba0c087d47c903e9/.github/npm/getBinary.js#L9) and [sbt-protodep](https://github.com/coralogix/sbt-protodep/blob/9a2132d2c1ccd6f3c9a939ba03f3ddd757031ee1/src/main/scala/com/coralogix/sbtprotodep/backends/BackendBinary.scala#L175) use `protofetch_windows_amd64.tar.gz`.
=> Fix windows artifact name

src/main.rs
This commit modifies the formatting of log messages to include the filename and line number of log messages, to facilitate debugging.
=> Print filename and line in log messages

src/cli/command_handlers.rs
When running `protofetch clean` when the proto output directory has already been removed, log an info message saying the directory has already been removed and there is nothing to do, rather than returning an error.
=> Don't error out when `clean` has already removed output dir

src/api/mod.rs, src/cli/command_handlers.rs, src/fetch.rs, src/model/protofetch/lock.rs, src/proto.rs
There is no need to make output directory name a part of the lock file, we can alway get it from the module file. Also, we allow overriding it from the command line, which goes against having it "locked" too.
=> Remove output dir from the lock file

src/fetch.rs, src/model/protofetch/lock.rs, src/proto.rs
Reverts https://github.com/coralogix/protofetch/pull/84.
This was a failed experiment, even with the `specifications` field the lock file doesn't contain enough information to resolve #83.
I'm going to implement a solution that doesn't rely on the `specifications` field, so let's remove it.
=> Remove specifications field from the lock file

Cargo.lock, Cargo.toml, src/cache.rs, src/fetch.rs, src/model/protofetch/mod.rs, src/proto_repository.rs
Previously, when a dependency tree contained multiple versions of the same dependency we used the following rules to resolve the conflicts:
1. Prefer lexicographically greater revisions.
2. If there is a branch specification and a revision specification, try to use both and fail if the revision tag is not reachable from the specified branch head.
There are a few problems with these rules:
- Rule 1 does not give user much control over transitive dependency versions. You can only override to a bigger revision.
- Lexicographic comparison does not necessarily make sense for revision strings.
- Rule 2 does not work with some git workflows.
- There are some corner cases when transitive dependencies change depending on the version we choose.  
I'd say the first problem is the most important one, …
=> Resolve to the "nearest" version

src/api/mod.rs, src/cli/command_handlers.rs, src/fetch.rs, src/lib.rs, src/main.rs, src/model/protofetch/lock.rs, src/model/protofetch/mod.rs, src/proto.rs, src/resolver/lock.rs, src/resolver/mod.rs
The PR is created as a draft, as it includes changes from https://github.com/coralogix/protofetch/pull/109.
Closes #83.
- `protofetch fetch`: updates `protofetch.lock` if `protofetch.toml` has changed. Previous behavior: ignore `protofetch.toml` even if changed, fetch whatever `protofetch.lock` says.
- `protofetch fetch --locked`: verifies that the lock file is up-to-date and fails otherwise
- `protofetch fetch --force-lock`: deprecated, but still works for backwards compatibility.
- `protofetch update`: recreates the lock file, like `fetch --force-lock` used to, but does not actually fetch the protos
It is possible to keep `--force-lock`, but I think it'd better to deprecate this flag:
- it's poorly named, the name looks like it forces protofetch to use the lock file, but in fact it's …
=> Update the lock file when necessary

src/api/builder.rs, src/api/mod.rs, src/cache.rs, src/cli/command_handlers.rs, src/cli/mod.rs, src/main.rs
- `--username` and `--password`: GIT credential helper is used instead for HTTP auth
- `--repo-output-directory`: there should be no reason to let a user override this
=> Remove deprecated CLI options

src/fetch.rs, src/resolver/git.rs, src/resolver/lock.rs, src/resolver/mod.rs
If `protofetch.toml` specifies a branch, having other commits on this branch should not be an error (but we still should use the commit from the lock file).
However, if `protofetch.toml` specifies a revision, and this revision starts resolving to a different commit, I think we should report this.
=> Do not fail if a branch has other commits than the lock file

src/cli/command_handlers.rs, src/resolver/lock.rs
We always generate a new lockfile to check if it is still up-to-date, but if nothing has changed, we shouldn't overwrite the file.
=> Only update the lock file if something has changed

src/api/builder.rs, src/api/mod.rs, src/cache.rs, src/cache/git.rs, src/cache/mod.rs, src/cli/command_handlers.rs, src/fetch.rs, src/git/cache.rs, src/git/mod.rs, src/git/repository.rs, src/lib.rs, src/proto.rs, src/resolver/git.rs
Includes commits from https://github.com/coralogix/protofetch/pull/113.
We don't need to hit network if we already know the commit hash from the lock file, and this commit is in the local cache. This makes repeated `protofetch fetch` runs fast.
=> Do not access remotes unless necessary

Cargo.lock, Cargo.toml, src/api/builder.rs, src/config.rs, src/lib.rs
Allow changing the cache location using the `PROTOFETCH_CACHE_DIR` environment variable.
This may be useful for example on CI if you want to move cache to some persistent location. It also prepares some infrastructure for other settings and for other configuration sources (like a config file).
=> Make cache dir configurable with an environment variable

README.md, src/api/builder.rs, src/config.rs, src/fetch.rs, src/git/cache.rs, src/model/protodep.rs, src/model/protofetch/lock.rs, src/model/protofetch/mod.rs, src/proto.rs
Most of the time git protocol should be a local decision, not part of the module descriptor. This PR makes it optional, and allows to configure the default protocol locally (for now only with an environment variable).
Closes #102
=> Make protocol optional and configurable locally

Cargo.lock, Cargo.toml, src/cache/git.rs, src/cache/mod.rs, src/cli/command_handlers.rs, src/fetch.rs, src/git/repository.rs, src/model/mod.rs, src/model/protodep.rs, src/model/protofetch/lock.rs, src/model/protofetch/mod.rs, src/model/protofetch/resolved.rs, src/proto.rs, src/resolver/git.rs, src/resolver/lock.rs, src/resolver/mod.rs
We have already broken lockfile compatibility in both directions (because of https://github.com/coralogix/protofetch/pull/106 old protofetch versions work incorrectly with new lock files, and because of https://github.com/coralogix/protofetch/pull/110 new protofetch versions cannot work with old lock files). I think it's a good opportunity to cleanup the lock file structure.
1. Add a version to the lock files.
2. Remove unnecessary fields that we duplicating `protofetch.toml` fields.
3. Flatten lockfile structure to make it more human-friendly.
4. Write URLs to the lock file instead of `forge`/`organization`/`repository`. The latter is github-focused, as other git hosting providers may have a different URL scheme. I'm not changing the code that parses the URL, so we still won't be able to …
=> Lockfile v2

src/api/builder.rs, src/config.rs
This will be especially useful after https://github.com/coralogix/protofetch/pull/119 lands, users will be able to configure default git protocol in the config file.
`dirs` says that on macOS config files should be in `/Users/Alice/Library/Application Support`, which I'm not sure about. I guess it follows the guidelines, but for CLI tools it's probably more common to use `/Users/Alice/.config`. Would be nice to hear your thoughts.
Closes https://github.com/coralogix/protofetch/issues/31
=> Allow configuring protofetch with a config file

src/config.rs
`~/.cache/protofetch` instead of `~/.protofetch/cache`. This is more standard, and also makes it less confusing — otherwise people may expect to find a config file in `~/.protofetch/...`, which is not the case. We will advise users to delete the old cache directory.
It makes sense to do it now, because we have already broken the lockfile compatibility, so users are likely to update.
=> Use a more standard cache directory

Cargo.lock, Cargo.toml, src/cli/command_handlers.rs, src/model/mod.rs, src/model/protofetch/mod.rs, src/proto.rs
Reduce build time by dropping unused dependencies, or dependencies that can be easily replaced.
Specifically:
- `regex` is relatively big, and we only need it to basically do `split('/')`. Replaced with much smaller `regex-lite` for now.
- `derive-new` was a bit overused, it's often safer to just build the structure explicitly, and it was the only create depending on `syn 1.x`.
- `strum` was only needed for one enum and is easy to replace
=> Update dependencies and drop unnecessary ones

Cargo.lock, Cargo.toml, src/git/cache.rs
This is a very limited fix for https://github.com/coralogix/protofetch/issues/124, that however should cover an important usecase of using protofetch from GitHub Actions, where GitHub host keys are pre-loaded to the global known host keys file.
=> Add a limited support for global known hosts file

.github/npm/.gitignore, .github/npm/getBinary.js, .github/npm/package.json, .github/npm/run.js, .github/npm/scripts.js
`binary-install` has open CVEs, and `simple-binary-install` seems to do the same thing, but with fewer dependencies.
=> Replace binary-install with simple-binary-install

Cargo.lock, Cargo.toml, src/git/cache.rs
1. Exponential backoff makes protofetch sometimes take too long to run.
2. It makes sense to initialize signal handlers to make sure the locks are removed when protofetch is killed.
=> Cache lock improvements

src/git/cache.rs, src/git/repository.rs
- When we know the commit hash, only fetch this commit (and its ancestors)
- When we only have a revision/branch, only fetch the relevant refs (and their ancestors).
This makes fetches significantly faster. For example, for googleapis/googleapis, it decreases the time from 1m20s to about 30s.
An even bigger improvement would be to
1. Shallow fetch. This is supported by libgit2 but I couldn't make it work.
2. Sparse checkout. This is not even supported by libgit2.
https://github.com/coralogix/protofetch/issues/137
=> Fetch optimizations

.github/workflows/ci.yml, flake.lock, flake.nix
Broken by https://github.com/coralogix/protofetch/pull/144, which made dependencies incompatible with the pinned rust toolchain.
This PR will check Nix Flake build on CI, but won't block PR merges if the check fails.
=> Fix nix flake build and check this on CI

src/git/repository.rs
While the configuration with `revision` and without a `branch` is not recommended, and fetching all branches is not very efficient, there are such `protofetch.toml` files in the wild, so we need to maintain the compatibility with them.
=> Fix fetching when no branch is specified

Cargo.lock, Cargo.toml, rust-toolchain.toml, src/flock.rs, src/git/cache.rs, src/lib.rs
The lock created by `gix-lock` is not cleared when the process is killed. This, however, seems to happen quite often when protofetch is used in a cargo build script and a project is opened in VSCode with rust-analyzer.
The lock implementation in this PR is resilient to such issues.
=> Use more robust cache locking

.github/workflows/ci.yml
The v3 actions have been deprecated and don't even work anymore.
Also, update the intel-based macOS runner, as macos-12 is no longer supported either.
=> Update upload/download artifact actions

CHANGELOG.md, Cargo.lock, Cargo.toml
* `protofetch`: 0.1.10 -> 0.1.11
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- Fix cache directory lock ([#157](https://github.com/coralogix/protofetch/pull/157))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.1.11
